<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'ProjectManagerModule\Module'                        => __DIR__ . '/Module.php',
    'ProjectManagerModule\Controller\SkeletonController' => __DIR__ . '/src/ProjectManagerModule/Controller/SkeletonController.php',
    'ProjectManagerModuleTest\Framework\TestCase'        => __DIR__ . '/tests/ProjectManagerModule/Framework/TestCase.php',
    'ProjectManagerModuleTest\SampleTest'                => __DIR__ . '/tests/ProjectManagerModule/SampleTest.php',
);